### ISSUE TITLE
Possibility to sign up for multiple events at the same time

### ISSUE THREAD

**Issue by Kaapelikala** [con2/konsti#741]
**Describe the bug**
Possibility to sign up for multiple events at the same time

**To Reproduce**

1. Go to 'ropekonsti'
2. Click on 'All Programs'
3. Scroll down to the events at the same time
4. Click both Sign Up dialogs open
5. Add some lag (either with massive amount of users or for example a bad internet connection or add throttling - Fast 3G seems to be enough

6. click Confirm on both at the same time
7. You will see a "You can't register to multiple events" for a while for one of them, but then both change to "You have signed up"
8. Go to My Programs and you'll see them both.

**Expected behavior**
I shouldn't be able to register to both. Only one of them.

**Screenshots**
one shows the final result, other shows (elements removed) registration that shows registration page
<img width="403" alt="2023-07-29 09_12_46-Konsti" src="https://github.com/ropekonsti/konsti/assets/1605729/8d7bca62-78e9-4efd-b5b7-e9644c0a463c">
<img width="344" alt="2023-07-29 09_11_36-Konsti" src="https://github.com/ropekonsti/konsti/assets/1605729/19cbdf23-f3f3-4bc5-b418-3ebe64f1720a">
)

**Desktop (please complete the following information):**

- OS: [Windows 10]
- Browser: Chrome

**Smartphone (please complete the following information):**

- Device: Nokia 8.3
- OS: -
- Browser Firefox

**Comment by Archinowsk** [comment]
Thank you for reporting this! You have the honor of opening our first GitHub issue 💎.

Since this is our first issue, we only now noticed it. I turned email notifications on so future issues should reach us faster.

Seems like a clear bug. I'll add it to our backlog.
